#!/bin/bash

export PATH="$(~/.dotfiles/custom_path.sh)"

# date -j +'%Y_%m_%d_%H_%M' >> ~/.phd_backup/test

threshold="36H"

displ_arg="-v-$threshold"

tm_fmt="$(cat ~/.phd_backup/backup_time_format)"

# get last time of backup
prev_time=$(tail -n 1 ~/.phd_backup/backup_success_times)

# get current time minus threshold (1d?), in same format
now=$(date -j $displ_arg +$tm_fmt)


if [[ $now > $prev_time ]]; then
	~/bin/phd_backup.py  # complete backup script
	# ~/bin/phd_rsync_net_backup
	# ~/bin/phd_backup_s3.py
	# ~/bin/vpn_mac_pro_backup
fi
