#!/bin/bash

export PATH="$(/Users/errollloyd/.dotfiles/custom_path.sh)"



tm_fmt="$(cat /Users/errollloyd/.mac_pro_backup/backup_time_format)"

# Purpose is to start a terminal window which runs backup scripts which require manual entry of passwords
# Gets run by crontab

# Checking if on uniwireless
# networksetup is macOS utilitity (all the network things)
# en0 is the Wi-Fi device (check with > networksetup -listnetworkserviceorder)
# "UniWireless" is name of network (see in system preferences - network)
# this variable will be empty if not connected to UniWireless
# use exit code of 0 for if connected, else 1 for not connected (grep exits with 1 when no lines selected)
uni_wireless=$(networksetup -getairportnetwork en0 | grep UniWireless)


# If not on uniwireless
if [[ "$?" == "1" ]]; then

	# the binary of Cisco's anytime connect
	# starts interactive prompt for logging into VPN - requires username (saved) and password
	# vpn -s connect remote.unimelb.edu.au/student
	/Users/errollloyd/bin/vpn_unimelb
fi

# once connected, ssh rsync will be run ... echo to make clear
echo -e "SSH R-sync into mac_pro (phd_mac_pro_backup)\n"

# perform rsync
/Users/errollloyd/bin/phd_mac_pro_backup


# $?, if previous command was phd_mac_pro, should be exit code of that script

if [[ "$?" == "0" ]]; then
	#Log time of backup into log
	date -j +$tm_fmt >> /Users/errollloyd/.mac_pro_backup/backup_log
	# escape sequences encode colors (92->green, 91->red)
	echo -e "\033[0;92m\nRSYNC --- success!!\n"
else
	echo -e "\033[0;91m\nRSYNC --- Not successful :(\n"
fi

# once rsync is done, disconnect
vpn disconnect